spring:
  application:
    name: sucursales
  datasource:
    # 1. URL: Por defecto usa tu MySQL de Laragon apuntando a mi_base_datos_dev. En Render usará la variable Postgres.
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/mi_base_datos_dev?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    # 2. Credenciales por defecto para tu Laragon
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    # 3. Driver: Por defecto el de MySQL. Render inyectará el de PostgreSQL.
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
  jpa:
    ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # 4. Dialecto crítico: Por defecto habla en MySQL para Laragon. En Render recibirá el de Postgres.
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.MySQL8Dialect}

server:
  port: ${PORT:8088}

# Habilitación técnica de OpenAPI y Swagger UI
springdoc:
  api-docs: 
    enabled: true
  swagger-ui: 
    enabled: true
    path: /swagger-ui.html

eureka:
  client:
    # En tu PC no buscará Eureka (evita errores), en Render pones la variable en true si lo necesitas
    register-with-eureka: ${REGISTER_EUREKA:false}
    fetch-registry: ${FETCH_EUREKA:false}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}